{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "ms_confirmarabrirlink"
	},
	"Message": "Deseas salir de la aplicación?",
	"Title": "Confirmar",
	"OKCaption": "Aceptar",
	"CancelCaption": "Cancelar"
}